
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: Nov 15 2020 16:41:38 EST (Nov 15 2020 21:41:38 UTC)

// Verification Directory fv/TMULT 

module TMULT(X_A, X_B, X_CLK, X_R, X_P);
  inout [3:0] X_A, X_B;
  inout X_CLK, X_R;
  inout [7:0] X_P;
  wire [3:0] X_A, X_B;
  wire X_CLK, X_R;
  wire [7:0] X_P;
  wire [3:0] A;
  wire [3:0] B;
  wire [7:0] P;
  wire CLK, R, UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4;
  wire UNCONNECTED5, UNCONNECTED6, UNCONNECTED7, UNCONNECTED8, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46;
  PDDW04DGZ_G IO_A0(.REN (1'b1), .I (1'b0), .OEN (1'b1), .PAD (X_A[0]),
       .C (A[0]));
  PDDW04DGZ_G IO_A1(.REN (1'b1), .I (1'b0), .OEN (1'b1), .PAD (X_A[1]),
       .C (A[1]));
  PDDW04DGZ_G IO_A2(.REN (1'b1), .I (1'b0), .OEN (1'b1), .PAD (X_A[2]),
       .C (A[2]));
  PDDW04DGZ_G IO_A3(.REN (1'b1), .I (1'b0), .OEN (1'b1), .PAD (X_A[3]),
       .C (A[3]));
  PDDW04DGZ_G IO_B0(.REN (1'b1), .I (1'b0), .OEN (1'b1), .PAD (X_B[0]),
       .C (B[0]));
  PDDW04DGZ_G IO_B1(.REN (1'b1), .I (1'b0), .OEN (1'b1), .PAD (X_B[1]),
       .C (B[1]));
  PDDW04DGZ_G IO_B2(.REN (1'b1), .I (1'b0), .OEN (1'b1), .PAD (X_B[2]),
       .C (B[2]));
  PDDW04DGZ_G IO_B3(.REN (1'b1), .I (1'b0), .OEN (1'b1), .PAD (X_B[3]),
       .C (B[3]));
  PDDW04DGZ_G IO_CLK(.REN (1'b1), .I (1'b0), .OEN (1'b1), .PAD (X_CLK),
       .C (CLK));
  PDDW04DGZ_G IO_P0(.REN (1'b1), .I (P[0]), .OEN (1'b0), .PAD (X_P[0]),
       .C (UNCONNECTED));
  PDDW04DGZ_G IO_P1(.REN (1'b1), .I (P[1]), .OEN (1'b0), .PAD (X_P[1]),
       .C (UNCONNECTED0));
  PDDW04DGZ_G IO_P2(.REN (1'b1), .I (P[2]), .OEN (1'b0), .PAD (X_P[2]),
       .C (UNCONNECTED1));
  PDDW04DGZ_G IO_P3(.REN (1'b1), .I (P[3]), .OEN (1'b0), .PAD (X_P[3]),
       .C (UNCONNECTED2));
  PDDW04DGZ_G IO_P4(.REN (1'b1), .I (P[4]), .OEN (1'b0), .PAD (X_P[4]),
       .C (UNCONNECTED3));
  PDDW04DGZ_G IO_P5(.REN (1'b1), .I (P[5]), .OEN (1'b0), .PAD (X_P[5]),
       .C (UNCONNECTED4));
  PDDW04DGZ_G IO_P6(.REN (1'b1), .I (P[6]), .OEN (1'b0), .PAD (X_P[6]),
       .C (UNCONNECTED5));
  PDDW04DGZ_G IO_P7(.REN (1'b1), .I (P[7]), .OEN (1'b0), .PAD (X_P[7]),
       .C (UNCONNECTED6));
  PDDW04DGZ_G IO_R(.REN (1'b1), .I (1'b0), .OEN (1'b1), .PAD (X_R), .C
       (R));
  TIEHIX1MA10TR TIHI(.Y (UNCONNECTED7));
  TIELOX1MA10TR TILO(.Y (UNCONNECTED8));
  DFFQX0P5MA10TR \P_reg[6] (.CK (CLK), .D (n_46), .Q (P[6]));
  DFFQX0P5MA10TR \P_reg[7] (.CK (CLK), .D (n_45), .Q (P[7]));
  NAND2X1BA10TR g1306__8780(.A (n_44), .B (n_43), .Y (n_46));
  OAI2XB1X1MA10TR g1307__4296(.A0 (R), .A1N (n_33), .B0 (n_44), .Y
       (n_45));
  A2DFFQX1MA10TR \P_reg[5] (.CK (CLK), .A (n_41), .B (n_0), .Q (P[5]));
  OR3X0P5MA10TR g1309__3772(.A (n_42), .B (n_34), .C (R), .Y (n_43));
  NAND3X1MA10TR g1310__1474(.A (n_42), .B (n_34), .C (n_0), .Y (n_44));
  A2DFFQX1MA10TR \P_reg[4] (.CK (CLK), .A (n_39), .B (n_0), .Q (P[4]));
  XOR3X1MA10TR g1312__4547(.A (n_40), .B (n_36), .C (n_31), .Y (n_41));
  OAI21X1MA10TR g1313__9682(.A0 (n_40), .A1 (n_36), .B0 (n_31), .Y
       (n_42));
  ADDFX1MA10TR g1314__2683(.A (n_35), .B (n_28), .CI (n_37), .S (n_39),
       .CO (n_40));
  A2DFFQX1MA10TR \P_reg[3] (.CK (CLK), .A (n_38), .B (n_0), .Q (P[3]));
  ADDFX1MA10TR g1316__1309(.A (n_29), .B (n_14), .CI (n_27), .S (n_38),
       .CO (n_37));
  ADDFX1MA10TR g1317__6877(.A (n_21), .B (n_2), .CI (n_24), .S (n_35),
       .CO (n_36));
  A2DFFQX1MA10TR \P_reg[2] (.CK (CLK), .A (n_32), .B (n_0), .Q (P[2]));
  AOI31X1MA10TR g1319__2900(.A0 (n_30), .A1 (A[3]), .A2 (B[3]), .B0
       (n_33), .Y (n_34));
  NOR2X1MA10TR g1320__2391(.A (n_30), .B (B[3]), .Y (n_33));
  XOR2X1MA10TR g1321__7675(.A (n_26), .B (n_16), .Y (n_32));
  ADDFX1MA10TR g1322__7118(.A (n_8), .B (n_3), .CI (n_22), .S (n_29),
       .CO (n_28));
  ADDFX1MA10TR g1323__8757(.A (n_1), .B (n_4), .CI (n_23), .S (n_31),
       .CO (n_30));
  OR2X1MA10TR g1324__1786(.A (n_25), .B (n_16), .Y (n_27));
  ADDHX1MA10TR g1325__5953(.A (n_17), .B (n_6), .S (n_26), .CO (n_25));
  A2DFFQX1MA10TR \P_reg[1] (.CK (CLK), .A (n_18), .B (n_0), .Q (P[1]));
  INVX1BA10TR g1327(.A (n_20), .Y (n_24));
  INVX1MA10TR g1328(.A (n_19), .Y (n_23));
  ADDHX1MA10TR g1329__5703(.A (n_5), .B (n_9), .S (n_22), .CO (n_21));
  ADDHX1MA10TR g1330__7114(.A (n_10), .B (n_13), .S (n_20), .CO (n_19));
  A2DFFQX1MA10TR \P_reg[0] (.CK (CLK), .A (n_7), .B (n_0), .Q (P[0]));
  NOR2X1MA10TR g1332__5266(.A (n_15), .B (n_16), .Y (n_18));
  XOR2X1MA10TR g1333__2250(.A (n_11), .B (n_12), .Y (n_17));
  AND2X1MA10TR g1334__6083(.A (n_6), .B (n_7), .Y (n_16));
  AOI22X1MA10TR g1335__2703(.A0 (B[1]), .A1 (A[0]), .B0 (A[1]), .B1
       (B[0]), .Y (n_15));
  NOR2BX1MA10TR g1336__5795(.AN (n_7), .B (n_13), .Y (n_14));
  NAND2X1AA10TR g1337__7344(.A (A[0]), .B (B[2]), .Y (n_12));
  NAND2X1AA10TR g1338__1840(.A (B[0]), .B (A[2]), .Y (n_11));
  AND2X1MA10TR g1339__5019(.A (B[1]), .B (A[3]), .Y (n_10));
  NAND2X1BA10TR g1340__1857(.A (A[2]), .B (B[2]), .Y (n_13));
  NAND2X1BA10TR g1341__9906(.A (B[0]), .B (A[3]), .Y (n_9));
  AND2X1MA10TR g1342__8780(.A (A[1]), .B (B[2]), .Y (n_8));
  AND2X1MA10TR g1343__4296(.A (B[0]), .B (A[0]), .Y (n_7));
  AND2X1MA10TR g1344__3772(.A (B[1]), .B (A[1]), .Y (n_6));
  AND2X1MA10TR g1345__1474(.A (B[1]), .B (A[2]), .Y (n_5));
  NAND2X1BA10TR g1346__4547(.A (B[2]), .B (A[3]), .Y (n_4));
  NAND2X1BA10TR g1347__9682(.A (A[0]), .B (B[3]), .Y (n_3));
  NAND2X1BA10TR g1348__2683(.A (A[1]), .B (B[3]), .Y (n_2));
  NAND2X1BA10TR g1349__1309(.A (A[2]), .B (B[3]), .Y (n_1));
  INVX1MA10TR g1350(.A (R), .Y (n_0));
endmodule

